[project]
name = "python-ia-predictions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "pandas>=2.2.3",
    "pyarrow>=17.0.0",
    "scikit-learn>=1.5.2",
]
